### ISSUE TITLE
Links to Kanboard + back

### ISSUE THREAD

**Issue by diego-betto** [BlueTeck/kanboard_chrome_extension#12]
Hi,

nice new ui, just some suggestion:

- [ ] links for single tasks/users to kanboard related pages
- [x] "back" link in overdue
- [ ] pin mode to keep window open (or open in new small popup)
- [x] compact mode: smaller icons and line height in projects list
- [ ] in options page set animation options: on/off, animation time

Thank you! Keep up your good work!

**Comment by BlueTeck** [comment]
- [ ] links for single tasks/users to kanboard related pages
- [x] "back" link in overdue
- [ ] pin mode to keep window open (or open in new small popup)
- [x] compact mode: smaller icons and line height in projects list
- [ ] in options page set animation options: on/off, animation time

Could you explain your first suggestion, unfortunately I don't understand it.

**Comment by diego-betto** [comment]
![2015-08-11 10_25_35-](https://cloud.githubusercontent.com/assets/11378282/9193433/9ec57726-4013-11e5-98cb-a9bfcc624535.png)

1. Link to Kanboard entry (ex. /project/20/task/57 )
2. Link to user details (ex. /?controller=user&action=show&user_id=1 )

**Comment by BlueTeck** [comment]
Regarding point 1, the Kanboard API needs an adjustment, issue created: https://github.com/fguillot/kanboard/issues/1330

**Comment by BlueTeck** [comment]
see https://github.com/BlueTeck/kanboard_angular/issues/9
