### ISSUE TITLE
Enhancement Request: Clock Page Shows Upcoming and Overdue

### ISSUE THREAD

**Issue by phillc73** [BlueTeck/kanboard_chrome_extension#15]
I think it would be very useful for the Overdue page, which is loaded when clicking the Alarm Clock icon anywhere in this app, also showed Upcoming tasks. e.g. Next 3 Tasks due.

If nothing is overdue, this page is not very useful. Adding the next three tasks, whatever the date range, could make this page always useful.

**Comment by BlueTeck** [comment]
https://github.com/BlueTeck/kanboard_angular/issues/8
