### ISSUE TITLE
Error due API call

### ISSUE THREAD

**Issue by diego-betto** [BlueTeck/kanboard_chrome_extension#9]
Hi, 

I receive error on loading tasks. 
Using Kanboard Stable version (v1.0.16)

Request: 
    {"jsonrpc": "2.0", "method": "getAllProjects", "id": 1}:

Response
   {"error": "Authentication failed"}

**Comment by BlueTeck** [comment]
Its working in my installation, maybe your auth token is wrong? Did it work with Kanboard 1.0.15 before?

**Comment by diego-betto** [comment]
Checked and changed, url and token are correct
Not tested on 1.0.15

**Comment by BlueTeck** [comment]
Could you please try to access the kanboard demo page http://kanboard.net/demo

API token: da2776e2c7ca07b2b1169099550aa4a197024f2f7aac21212682240acc3f
API endpoint:  http://demo.kanboard.net/jsonrpc.php

**Comment by diego-betto** [comment]
Demo works

**Comment by diego-betto** [comment]
debug.log
[2015-06-30 07:38:33] [debug] START_REQUEST=/board/?controller=app&action=status&_=1435655339162
[2015-06-30 16:38:33] [debug] SELECT * FROM "actions"
[2015-06-30 16:38:33] [debug] DURATION=0.0027108192443848
[2015-06-30 16:38:33] [debug] SELECT * FROM "action_has_params"
[2015-06-30 16:38:33] [debug] DURATION=0.00014400482177734
[2015-06-30 16:38:33] [debug] SELECT 1 FROM "users"  WHERE "id" = ?
[2015-06-30 16:38:33] [debug] DURATION=0.00025486946105957
[2015-06-30 16:38:33] [debug] SQL_QUERIES=3
[2015-06-30 16:38:33] [debug] RENDERING=0.065348148345947
[2015-06-30 16:38:33] [debug] END_REQUEST=/board/?controller=app&action=status&_=1435655339162

**Comment by diego-betto** [comment]
Uhm... how do you send user credentials?

**Comment by BlueTeck** [comment]
i think the log does not respond to the api call.
I will try the 3rd level on my own server later.

The user credentioals are sent via http basic auth -> http://kanboard.net/documentation/api-json-rpc

**Comment by diego-betto** [comment]
Ok thank you.
But api keys are different for every user in the same Kanboard?
If yes ok, if not, where I set my username/password?

**Comment by BlueTeck** [comment]
It is not a 3level problem, http://demo.kanboard.net/jsonrpc.php is also a subdomain.

Could you make a screenshot of your dev console with your request header? Is the authorization set?
![image](https://cloud.githubusercontent.com/assets/1961634/8541026/31911e1a-248b-11e5-8c70-6a19c711afed.png)

**Comment by diego-betto** [comment]
Yes is set
![kanboard_screenshot](https://cloud.githubusercontent.com/assets/11378282/8568064/c62c16bc-256a-11e5-9845-03f1085ffeb4.png)

**Comment by diego-betto** [comment]
Any clue?

**Comment by BlueTeck** [comment]
looks good.... i think it is not a extension problem.... anyway, i am only a few days away from a new extension release with complete new code, maybe it is working afterwards, but i think it is a problem with your kanboard installation. maybe you should try to access the api with another tool to test.

**Comment by diego-betto** [comment]
Ok thank you!

**Comment by diego-betto** [comment]
Nice update, but problem persists.

Maybe a need to use or set something? I use a "remote account", is administrator, 2fa not enabled.
Other Requirements?

**Comment by BlueTeck** [comment]
What do you mean by "remote account"?

For the API the user is not important, because there is an api user called jsonrpc. You just have to copy the settings from http://***********/board/?controller=config&action=api

**Comment by diego-betto** [comment]
Ok thank you. Settings are copied correctly. I'll try another hosting :)

**Comment by diego-betto** [comment]
Changed hosting. Seems to run correctly.

Thank you for your support :)
